# Generated by Django 4.0.2 on 2022-02-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='media/images/'),
            preserve_default=False,
        ),
    ]
