# Generated by Django 4.0.3 on 2023-01-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_slider_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAgroAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OffreuAssurance', models.CharField(max_length=300)),
                ('TypeAssurance', models.CharField(max_length=300)),
                ('CulturAssure', models.CharField(max_length=300)),
                ('NivPrime', models.CharField(max_length=300)),
            ],
        ),
    ]
