# Generated by Django 4.0.3 on 2023-01-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_dimagroassurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAgroCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZonProd_Cult', models.CharField(max_length=300)),
                ('Cultur_Pratique', models.CharField(max_length=300)),
                ('Type_Semence', models.CharField(max_length=300)),
                ('CodeVarietesCultiv', models.IntegerField()),
                ('VarieteCultive', models.CharField(max_length=300)),
                ('Appro_Intrant_mat', models.CharField(max_length=300)),
                ('SourcApprovisIntran', models.CharField(max_length=300)),
                ('SourcApprovisSemenc', models.CharField(max_length=300)),
                ('SourcApprovisEngrProdPhyto', models.CharField(max_length=300)),
                ('SourcApprovisMatAgro', models.CharField(max_length=300)),
                ('TypeAcquisIntran', models.CharField(max_length=300)),
                ('TypeAcquisMat', models.CharField(max_length=300)),
                ('TypeFertilisUtil', models.CharField(max_length=300)),
                ('TypePesticidUtil', models.CharField(max_length=300)),
                ('ModAcquisParcel', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OffreServicFinance', models.CharField(max_length=300)),
                ('DemandApport', models.IntegerField()),
                ('TypeGaranExige', models.CharField(max_length=300)),
                ('LongProcedCredi', models.IntegerField()),
                ('DelaiRembourse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Organisation', models.CharField(max_length=300)),
                ('TypeServicOfferOP', models.CharField(max_length=300)),
                ('BesoinForm', models.CharField(max_length=300)),
                ('ContrainGlobalAgro', models.CharField(max_length=300)),
                ('ContrainMajFilier', models.CharField(max_length=300)),
                ('InfrasStockCondition', models.CharField(max_length=300)),
                ('FournisEmballag', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Production', models.CharField(max_length=300)),
                ('ProdCultHiver', models.CharField(max_length=300)),
                ('TypeSolExist', models.CharField(max_length=300)),
                ('TypeDegradZonCultur', models.CharField(max_length=300)),
                ('CauseDegrad', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroVarieteCultive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameVarietesCultiv', models.IntegerField()),
                ('Arachide', models.CharField(max_length=300)),
                ('Mil', models.CharField(max_length=300)),
                ('Maïs', models.CharField(max_length=300)),
                ('Niébé', models.CharField(max_length=300)),
                ('Pastèque', models.CharField(max_length=300)),
                ('Oignon', models.CharField(max_length=300)),
                ('Tomate', models.CharField(max_length=300)),
                ('Piment', models.CharField(max_length=300)),
                ('Jaxaatou', models.CharField(max_length=300)),
                ('Pomme_de_terre', models.CharField(max_length=300)),
                ('Chou_Pomme', models.CharField(max_length=300)),
                ('Mangue', models.CharField(max_length=300)),
                ('Papaye', models.CharField(max_length=300)),
                ('Citron', models.CharField(max_length=300)),
                ('Orange', models.CharField(max_length=300)),
            ],
        ),
    ]
